

# espanhol

printf "\n Baixando audios de Espanhol"

wget http://wpanet.wordproject.com/bibles/app/audio/6_1.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_2.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_3.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_4.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_5.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_6.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_7.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_8.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_9.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_10.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_11.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_12.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_13.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_14.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_15.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_16.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_17.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_18.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_19.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_20.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_21.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_22.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_23.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_24.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_25.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_26.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_27.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_28.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_29.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_30.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_31.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_32.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_33.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_34.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_35.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_36.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_37.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_38.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_39.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_40.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_41.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_42.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_43.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_44.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_45.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_46.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_47.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_48.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_49.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_50.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_51.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_52.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_53.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_54.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_55.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_56.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_57.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_58.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_59.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_60.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_61.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_62.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_63.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_64.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_65.zip
wget http://wpanet.wordproject.com/bibles/app/audio/6_66.zip

# Alemao

printf "\n Baixando audios de Alemao"

wget http://wpanet.wordproject.com/bibles/app/audio/9_1.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_2.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_3.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_4.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_5.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_6.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_7.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_8.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_9.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_10.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_11.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_12.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_13.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_14.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_15.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_16.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_17.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_18.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_19.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_20.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_21.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_22.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_23.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_24.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_25.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_26.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_27.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_28.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_29.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_30.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_31.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_32.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_33.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_34.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_35.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_36.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_37.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_38.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_39.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_40.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_41.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_42.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_43.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_44.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_45.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_46.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_47.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_48.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_49.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_50.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_51.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_52.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_53.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_54.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_55.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_56.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_57.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_58.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_59.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_60.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_61.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_62.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_63.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_64.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_65.zip
wget http://wpanet.wordproject.com/bibles/app/audio/9_66.zip